### ISSUE TITLE
amdvlk Q4.2 and Q4.3 crashes with core dump, Q4.1 works.

### ISSUE THREAD

**Issue by staalmannen** [GPUOpen-Drivers/AMDVLK#190]
OS: Arch linux
Driver: amdgpu (19.1.0-2 ) ; radeon blacklisted

env VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/amd_icd64.json vulkaninfo also crashes, so not a problem of competing drivers (also no other vulkan drivers installed)

lspci -v | grep VGA 
VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Mullins [Radeon R4/R5 Graphics] (rev 45) (prog-if 00 [VGA controller])

gdb vulkaninfo (Q4.3):

```(gdb) run
Starting program: /usr/bin/vulkaninfo
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
ERROR: [Loader Message] Code 0 : /usr/lib32/amdvlk32.so: wrong ELF class: ELFCLASS32

Program received signal SIGABRT, Aborted.
0x00007ffff7a50615 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7a50615 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff7a39862 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff66264e4 in ?? () from /usr/lib/amdvlk64.so
#3  0x00007ffff48af4e6 in ?? () from /usr/lib/amdvlk64.so
#4  0x00007ffff48a6a4a in ?? () from /usr/lib/amdvlk64.so
#5  0x00007ffff48a8ffa in ?? () from /usr/lib/amdvlk64.so
#6  0x00007ffff48a91b9 in ?? () from /usr/lib/amdvlk64.so
#7  0x00007ffff460fd85 in ?? () from /usr/lib/amdvlk64.so
#8  0x00007ffff459a407 in ?? () from /usr/lib/amdvlk64.so
#9  0x00007ffff45ce7ff in ?? () from /usr/lib/amdvlk64.so
#10 0x00007ffff48a3360 in ?? () from /usr/lib/amdvlk64.so
#11 0x00007ffff7854337 in ?? () from /usr/lib/libvulkan.so
#12 0x00007ffff785e5a0 in ?? () from /usr/lib/libvulkan.so
#13 0x00007ffff785f1fd in ?? () from /usr/lib/libvulkan.so
#14 0x00007ffff78621a1 in vkCreateDevice () from /usr/lib/libvulkan.so
#15 0x00005555555c0604 in ?? ()
#16 0x0000555555564938 in ?? ()
#17 0x00007ffff7a3b152 in __libc_start_main () from /usr/lib/libc.so.6
#18 0x0000555555566bee in ?? () ```

**Comment by staalmannen** [comment]
amdvlk Q4.4 works so whatever was wrong in Q4.2 and Q4.3 is now solved.
