### ISSUE TITLE
Not able to build the AMDVLK

### ISSUE THREAD

**Issue by gmmo** [GPUOpen-Drivers/AMDVLK#338]
Hi, I am trying to build the AMD Vulkan driver following these instructions on Ubuntu

https://github.com/GPUOpen-Drivers/AMDVLK/blob/dev/README.md

But keeps failing as below. Not sure if the problem is the repo. Any clues how I can get passed this?

thank you very much.

my ubuntu version

```
gustavo@ubuntu:~/vulkandriver$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
```

```
gustavo@ubuntu:~/vulkandriver$ python --version
Python 3.8.10
gustavo@ubuntu:~/vulkandriver$ git --version
git version 2.25.1
gustavo@ubuntu:~/vulkandriver$ repo init -u https://github.com/GPUOpen-Drivers/AMDVLK.git -b master
/home/gustavo/vulkandriver/.repo/repo/main.py:569: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn("\n... A new version of repo (%s) is available.", exp_str)

... A new version of repo (2.37) is available.
/home/gustavo/vulkandriver/.repo/repo/main.py:571: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn(
... You should upgrade soon:
    cp /home/gustavo/vulkandriver/.repo/repo/repo /home/gustavo/bin/repo

repo: reusing existing repo client checkout in /home/gustavo/vulkandriver
.repo/manifests/: discarding 135 commits

Traceback (most recent call last):
  File "/home/gustavo/vulkandriver/.repo/repo/main.py", line 876, in <module>
    _Main(sys.argv[1:])
  File "/home/gustavo/vulkandriver/.repo/repo/main.py", line 852, in _Main
    result = repo._Run(name, gopts, argv) or 0
  File "/home/gustavo/vulkandriver/.repo/repo/main.py", line 298, in _Run
    result = run()
  File "/home/gustavo/vulkandriver/.repo/repo/main.py", line 281, in <lambda>
    run = lambda: self._RunLong(name, gopts, argv) or 0
  File "/home/gustavo/vulkandriver/.repo/repo/main.py", line 447, in _RunLong
    execute_command()
  File "/home/gustavo/vulkandriver/.repo/repo/main.py", line 413, in execute_command
    execute_command_helper()
  File "/home/gustavo/vulkandriver/.repo/repo/main.py", line 379, in execute_command_helper
    result = cmd.Execute(copts, cargs)
  File "/home/gustavo/vulkandriver/.repo/repo/subcmds/init.py", line 393, in Execute
    self._ConfigureUser(opt)
  File "/home/gustavo/vulkandriver/.repo/repo/subcmds/init.py", line 213, in _ConfigureUser
    name = self._Prompt("Your Name", mp.UserName)
  File "/home/gustavo/vulkandriver/.repo/repo/project.py", line 753, in UserName
    self._LoadUserIdentity()
  File "/home/gustavo/vulkandriver/.repo/repo/project.py", line 766, in _LoadUserIdentity
    u = self.bare_git.var("GIT_COMMITTER_IDENT")
  File "/home/gustavo/vulkandriver/.repo/repo/project.py", line 3695, in runner
    p.Wait()
  File "/home/gustavo/vulkandriver/.repo/repo/git_command.py", line 501, in Wait
    self.VerifyCommand()
  File "/home/gustavo/vulkandriver/.repo/repo/git_command.py", line 491, in VerifyCommand
    raise GitCommandError(
git_command.GitCommandError: GitCommandError: git command failure
    Project: manifests
    Args: var GIT_COMMITTER_IDENT
    Stdout:
None
    Stderr:
```

**Comment by Flakebi** [comment]
This looks like a problem with either your `git` package or your `repo` package. Can you try updating your `repo` to the latest available version and see if this fixes the issue?
The commands are at the very bottom of the repo page: https://gerrit.googlesource.com/git-repo
