### ISSUE TITLE
AMDVLK on systems with hybrid graphics?

### ISSUE THREAD

**Issue by xDShot** [GPUOpen-Drivers/AMDVLK#49]
Has anyone luck making it work on systems with dual graphics?

OS: Arch Linux. AMDVLK is installed through https://aur.archlinux.org/packages/amdvlk-git

I have PC with intel hd 4600 + amd radeon 8750m. It does work with mesa vulkan-radeon drivers, but not with AMDVLK. For ex launching vkQuake:

```
[xdshot@lenovo-pc Quake]$ VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/amd_icd64.json WINEPREFIX=~/wineprefixes/win64/ DRI_PRIME=1 wine vkQuake.exe
000b:fixme:winediag:start_process Wine Staging 3.13 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
000b:err:wineboot:ProcessRunKeys Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2)
Command line: Z:\home\xdshot\vkQuake\Quake\vkQuake.exe
Found SDL version 2.0.8
Detected 4 CPUs.
Quake 1.09 (c) id Software
GLQuake 1.00 (c) id Software
FitzQuake 0.85 (c) John Fitzgibbons
FitzQuake SDL port (c) SleepwalkR, Baker
QuakeSpasm 0.93.0 (c) Ozkan Sezer, Eric Wasylishen & others
vkQuake 1.00.0 (c) Axel Gneiting & others
Host_Init
Playing registered version.
Console initialized.
UDP Initialized
WIPX_OpenSocket: Protocol not supported
WIPX_Init: Unable to open control socket, IPX disabled
Server using protocol 666 (FitzQuake)
Exe: 15:52:13 Jul 27 2018
256.0 megabyte heap

ERROR-OUT BEGIN


QUAKE ERROR: Couldn't create window: Installed Vulkan doesn't implement the VK_KHR_surface extension

[xdshot@lenovo-pc Quake]$
```

**Comment by xDShot** [comment]
```
[xdshot@lenovo-pc bin]$ LANG=en VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/amd_icd64.json DRI_PRIME=1 gdb vulkaninfo
GNU gdb (GDB) 8.1.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Registered pretty printers for UE4 classes
Reading symbols from vulkaninfo...(no debugging symbols found)...done.
(gdb) cont
The program is not being run.
(gdb) start
Function "main" not defined.
Make breakpoint pending on future shared library load? (y or [n])  
Starting program: /usr/bin/vulkaninfo 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
==========
VULKANINFO
==========

Vulkan Instance Version: 1.1.82


Program received signal SIGSEGV, Segmentation fault.
0x00007ffff54b581f in Pal::AddrMgr::Init (this=<optimized out>) at /usr/src/debug/pal/src/core/addrMgr/addrMgr.cpp:91
91	/usr/src/debug/pal/src/core/addrMgr/addrMgr.cpp: No such file or directory.
(gdb) bt
#0  0x00007ffff54b581f in Pal::AddrMgr::Init (this=<optimized out>) at /usr/src/debug/pal/src/core/addrMgr/addrMgr.cpp:91
#1  0x00007ffff54d0c33 in Pal::AddrMgr1::Create (ppAddrMgr=<optimized out>, pPlacementAddr=<optimized out>, pDevice=<optimized out>)
    at /usr/src/debug/pal/src/core/addrMgr/addrMgr1/addrMgr1.cpp:57
#2  Pal::Device::HwlEarlyInit (this=<optimized out>) at /usr/src/debug/pal/src/core/device.cpp:553
#3  0x00007ffff5310d88 in Pal::Device::EarlyInit(Pal::HwIpLevels const&) [clone .constprop.777] (this=0x5555556208d0, ipLevels=...)
    at /usr/src/debug/pal/src/core/device.cpp:423
#4  0x00007ffff54aefdb in Pal::Linux::Device::EarlyInit (this=<optimized out>, ipLevels=...) at /usr/src/debug/pal/src/core/os/lnx/lnxDevice.cpp:617
#5  0x00007ffff54a1623 in Pal::Linux::Platform::ReQueryDevices (this=<optimized out>) at /usr/src/debug/pal/src/core/os/lnx/lnxDevice.cpp:218
#6  0x00007ffff54c8539 in Pal::Platform::ReEnumerateDevices (this=<optimized out>) at /usr/src/debug/pal/src/core/platform.cpp:599
#7  Pal::Platform::Init (this=<optimized out>, this=<optimized out>) at /usr/src/debug/pal/src/core/platform.cpp:332
#8  0x00007ffff530dd87 in Pal::Platform::Create (ppPlatform=<synthetic pointer>, pPlacementAddr=0x555555614e10, allocCb=..., createInfo=...)
    at /usr/src/debug/pal/src/core/platform.cpp:165
#9  Pal::CreatePlatform (ppPlatform=<optimized out>, pPlacementAddr=0x555555614e10, createInfo=...) at /usr/src/debug/pal/src/core/libInit.cpp:165
#10 vk::Instance::Init(VkApplicationInfo const*) [clone .constprop.873] (this=<optimized out>, pAppInfo=<optimized out>)
    at /usr/src/debug/xgl/icd/api/vk_instance.cpp:315
#11 0x00007ffff54f57c1 in vk::Instance::Create (pCreateInfo=<optimized out>, pAllocator=<optimized out>, pInstance=<optimized out>)
    at /usr/src/debug/xgl/icd/api/vk_instance.cpp:198
#12 0x00007ffff7d2411e in ?? () from /usr/lib/libvulkan.so.1
#13 0x00007ffff7d27d19 in ?? () from /usr/lib/libvulkan.so.1
#14 0x00007ffff7d2bdfe in vkCreateInstance () from /usr/lib/libvulkan.so.1
#15 0x0000555555556522 in ?? ()
#16 0x00007ffff7b5f223 in __libc_start_main () from /usr/lib/libc.so.6
#17 0x0000555555558d2e in _start ()
(gdb)
```

**Comment by jfactory07** [comment]
Can you try to install firmware. it seems you need install firmware from oland:
1. Download https://www2.ati.com/drivers/linux/ubuntu/amdgpu-pro-17.40-514569.tar.xz
2. xz -d amdgpu-pro-17.40-514569.tar.xz && tar xvf amdgpu-pro-17.40-514569.tar
3. cd amdgpu-pro-17.40-514569
4. dpkg -x amdgpu-pro-dkms_17.40-514569_all.deb dkms
5. oland firmwares locates under dkms/usr/src/amdgpu-17.40-514569/firmware/radeon

you got the same issue as: https://github.com/GPUOpen-Drivers/AMDVLK/issues/46

**Comment by JacobHeAMD** [comment]
Please also make sure that radeon is in blacklist, and amdgpu is modprobed. It would be helpful if pasting the "dmesg".
