### ISSUE TITLE
Segfault with 4.18 kernel on ubuntu 18.04

### ISSUE THREAD

**Issue by inferrna** [GPUOpen-Drivers/AMDVLK#51]
my system is
```
Ubuntu 18.04
linux kernel 4.18.5
mesa 18.2-rc5
GPU polaris11 (rx460)
CPU xeon 2665 (8/16)
```
 My xorg.conf:
```
Section "Device"
	Identifier  "radeon"
	Driver      "amdgpu"
	Option      "DRI3" "1"
        Option      "TearFree" "true"
        Option      "AccelMethod" "glamor"
EndSection
```

both samples and amdvlk driver compiled with gcc-8

Running sample from https://github.com/SaschaWillems/Vulkan
```gdb
(gdb) run
Starting program: /tmp/Vulkan/vulkan-demos/bin/textoverlay 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff2c17be4 in vk::GenerateRenderPassHash(vk::RenderPassCreateInfo const*) () from /usr/lib/x86_64-linux-gnu/amdvlk64.so
(gdb) bt
#0  0x00007ffff2c17be4 in vk::GenerateRenderPassHash(vk::RenderPassCreateInfo const*) () from /usr/lib/x86_64-linux-gnu/amdvlk64.so
#1  0x00007ffff2c1f493 in VkResult vk::CreateRenderPass<VkRenderPassCreateInfo>(vk::Device*, VkRenderPassCreateInfo const*, VkAllocationCallbacks const*, VkRenderPass_T**) [clone .lto_priv.1752] () from /usr/lib/x86_64-linux-gnu/amdvlk64.so
#2  0x0000555555576d7a in VulkanExampleBase::setupRenderPass() ()
#3  0x000055555557e7be in VulkanExampleBase::prepare() ()
#4  0x00005555555731fb in VulkanExample::prepare() ()
#5  0x0000555555566b2d in main ()
(gdb) quit
```
Also failed wine+dxvk. With radv driver both samples and wine+dxvk runs fine.

**Comment by Francesco149** [comment]
you might need to upgrade to kernel 4.19-rc2 or copy firmware files from amdgpu as instructed here https://github.com/GPUOpen-Drivers/AMDVLK/issues/50#issuecomment-419015191

**Comment by amingriyue** [comment]
Is the issue still there?

**Comment by amingriyue** [comment]
Could I know which sample you run into this issue?

**Comment by amingriyue** [comment]
cannot reproduce it with kernel18.5+latest amdvlk driver.
