### ISSUE TITLE
Segfault on latest amd-staging-drm-next kernel

### ISSUE THREAD

**Issue by mcoffin** [GPUOpen-Drivers/AMDVLK#97]
Both the binary builds and a built-from-source version of the AMDVLK driver segfault on the latest [`amd-staging-drm-next`](https://cgit.freedesktop.org/~agd5f/linux/log/?h=amd-staging-drm-next) kernel.

I've tried updating the headers in [`drivers/pal/src/core/os/amdgpu/include/drm`](https://github.com/GPUOpen-Drivers/pal/tree/dev/src/core/os/amdgpu/include/drm) to match the kernel's in terms of what was removed from them, but had no luck.

Any help that can be offered would be appreciated.

**Comment by mcoffin** [comment]
If I want to build for a non-default kernel, what headers do I have to update (if any)? Since the segfault only occurs on the `amd-staging-drm-next` kernel but not on `5.1.9`, I'm assuming that some kind of difference in an `ioctl` might be to blame?

**Comment by mcoffin** [comment]
Here's the stacktrace for the `v-2019.Q2.5` release with debug info.

```
Reading symbols from bin/mesh...
(No debugging symbols found in bin/mesh)
(gdb) run
Starting program: /home/mcoffin/secure/vulkan-examples/builds/Release64/bin/mesh
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
BFD: warning: /home/mcoffin/secure/amdvlk/drivers/xgl/builds/Debug64/icd/amdvlk64.so: corrupt GNU_PROPERTY_TYPE (5) size: 0
AMD-PAL: Warn: Unconditional Alert | Reason: Unknown (/home/mcoffin/secure/amdvlk/drivers/pal/inc/util/palMemTrackerImpl.h:76:~MemTracker)
AMD-PAL: Warn: ================ List of Leaked Blocks ================ (/home/mcoffin/secure/amdvlk/drivers/pal/inc/util/palMemTrackerImpl.h:338:MemoryReport)
AMD-PAL: Warn: ClientMem = 0x0x555555668720, AllocSize =     1424, MemBlkType = New, File = /home/mcoffin/secure/amdvlk/drivers/pal/src/core/os/amdgpu/amdgpuVamMgr.cpp, LineNumber =      458, AllocNum =        1 (/home/mcoffin/secure/amdvlk/drivers/pal/inc/util/palMemTrackerImpl.h:349:MemoryReport)
AMD-PAL: Warn: ================ End of List =========================== (/home/mcoffin/secure/amdvlk/drivers/pal/inc/util/palMemTrackerImpl.h:352:MemoryReport)

Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) backtrace
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff17bc3cd in Pal::Amdgpu::Device::ConveySyncObjectState (this=0x555555739e20, importSyncObj=20, importPoint=0, exportSyncObj=11, exportPoint=0)
    at /home/mcoffin/secure/amdvlk/drivers/pal/src/core/os/amdgpu/amdgpuDevice.cpp:3345
#2  0x00007ffff17cb8c6 in Pal::Amdgpu::Queue::DoAssociateFenceWithLastSubmit (this=0x5555559eca80, pFence=0x5555559089c8)
    at /home/mcoffin/secure/amdvlk/drivers/pal/src/core/os/amdgpu/amdgpuQueue.cpp:1032
#3  0x00007ffff17ca4cf in Pal::Amdgpu::Queue::OsSubmit (this=0x5555559eca80, submitInfo=..., internalSubmitInfo=...)
    at /home/mcoffin/secure/amdvlk/drivers/pal/src/core/os/amdgpu/amdgpuQueue.cpp:632
#4  0x00007ffff17a1bed in Pal::Queue::SubmitInternal (this=0x5555559eca80, submitInfo=..., postBatching=false)
    at /home/mcoffin/secure/amdvlk/drivers/pal/src/core/queue.cpp:370
#5  0x00007ffff15efd24 in Pal::Queue::Submit (this=0x5555559eca80, submitInfo=...) at /home/mcoffin/secure/amdvlk/drivers/pal/src/core/queue.h:177
#6  0x00007ffff02c7211 in vk::Queue::Submit (this=0x5555559ec978, submitCount=1, pSubmits=0x7fffffffdb80, fence=0x555555908990)
    at ../../icd/api/vk_queue.cpp:365
#7  0x00007ffff02c93ab in vk::entry::vkQueueSubmit (queue=0x5555559ec970, submitCount=1, pSubmits=0x7fffffffdb80, fence=0x555555908990)
    at ../../icd/api/vk_queue.cpp:1239
#8  0x00005555555808a4 in vks::UIOverlay::prepareResources() ()
#9  0x000055555558a779 in VulkanExampleBase::prepare() ()
#10 0x000055555557ce32 in VulkanExample::prepare() ()
#11 0x000055555556c133 in main ()
```

**Comment by mcoffin** [comment]
Ok, I figured this out. With the new kernel reporting the timeline functions, I had to update libdrm to the latest version to make it work. This comment should help people arriving here via google, but this isn't an AMDVLK problem.
